# Generated by Django 5.0.6 on 2026-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('front_seo_title', models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для главной')),
                ('front_seo_description', models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для главной')),
            ],
            options={
                'verbose_name': 'Настройки и главная',
                'verbose_name_plural': 'Настройки и главная',
                'db_table': '_front',
            },
        ),
    ]
