# Generated by Django 5.0.6 on 2026-01-03 22:17

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_front', models.BooleanField(default=True, verbose_name='Отображать на главной')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, help_text='530x380', upload_to='front/', verbose_name='Фото врача')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
                'db_table': 'diploms',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('phone', models.CharField(max_length=512, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок')),
                ('seo_description', models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-описание')),
                ('type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видео')], default=('article', 'Статья'), max_length=128, verbose_name='Тип поста')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Вводный текст')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('thumbnail', models.ImageField(help_text='760x480', upload_to='posts/', verbose_name='Картинка в списке')),
                ('video', models.TextField(blank=True, verbose_name='Видео')),
                ('photo', models.ImageField(blank=True, help_text='2360x800', upload_to='posts/', verbose_name='Картинка в статье')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'articles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_on_front', models.BooleanField(default=True, verbose_name='Отображать на главной')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='front',
            name='about_desc',
            field=tinymce.models.HTMLField(default='-', verbose_name='Текст в блоке "О враче"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='front',
            name='about_seo_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для страницы "О враче"'),
        ),
        migrations.AddField(
            model_name='front',
            name='about_seo_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для страницы "О враче"'),
        ),
        migrations.AddField(
            model_name='front',
            name='about_text',
            field=tinymce.models.HTMLField(default='-', verbose_name='Текст на странице "О враче"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='front',
            name='articles_seo_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для страницы "Статьи"'),
        ),
        migrations.AddField(
            model_name='front',
            name='articles_seo_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для страницы "Статьи"'),
        ),
        migrations.AddField(
            model_name='front',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='front',
            name='front_desc',
            field=models.CharField(default='', max_length=256, verbose_name='Вводный текст на главной'),
        ),
        migrations.AddField(
            model_name='front',
            name='front_heading',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок на главной'),
        ),
        migrations.AddField(
            model_name='front',
            name='ok',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Одноклассники'),
        ),
        migrations.AddField(
            model_name='front',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='front',
            name='photo',
            field=models.ImageField(default='-', help_text='900x732', upload_to='front/', verbose_name='Фото врача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='front',
            name='point_1',
            field=models.CharField(blank=True, default='', help_text='Для выделения большими - тег <b>', max_length=256, verbose_name='Пункт 1 в блоке "О враче"'),
        ),
        migrations.AddField(
            model_name='front',
            name='point_2',
            field=models.CharField(blank=True, default='', help_text='Для выделения большими - тег <b>', max_length=256, verbose_name='Пункт 2 в блоке "О враче"'),
        ),
        migrations.AddField(
            model_name='front',
            name='reviews_seo_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для страницы "Отзывы"'),
        ),
        migrations.AddField(
            model_name='front',
            name='reviews_seo_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для страницы "Отзывы"'),
        ),
        migrations.AddField(
            model_name='front',
            name='tg',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='front',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Вконтакте'),
        ),
        migrations.AddField(
            model_name='front',
            name='wa',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Whatsapp'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-описание')),
                ('show_on_front', models.BooleanField(default=True, verbose_name='Отображать на главной')),
                ('empty', models.BooleanField(default=False, verbose_name='Не открывать страницу')),
                ('favorite', models.BooleanField(default=False, verbose_name='Выделить на странцие услуг')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, help_text='2360x800', upload_to='services/', verbose_name='Картинка в статье')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='front.service', verbose_name='Родительская услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('meta_title', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, default='', max_length=256, verbose_name='Мета-описание')),
                ('question', models.CharField(max_length=512, verbose_name='Вопрос')),
                ('answer', tinymce.models.HTMLField(verbose_name='Ответ')),
                ('services', models.ManyToManyField(blank=True, related_name='faq', to='front.service', verbose_name='В каких устугах отображать вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'db_table': 'faq',
            },
        ),
    ]
