# Generated by Django 5.0.6 on 2026-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_diplom_order_page_post_review_front_about_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='services_seo_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для страницы "Услуги"'),
        ),
        migrations.AddField(
            model_name='front',
            name='services_seo_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для страницы "Услуги"'),
        ),
    ]
