# Generated by Django 5.0.6 on 2026-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_front_services_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='contacts_seo_description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО описание для страницы "Контакты"'),
        ),
        migrations.AddField(
            model_name='front',
            name='contacts_seo_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='СЕО заголовок для страницы "Контакты"'),
        ),
    ]
