# Generated by Django 5.0.6 on 2026-01-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_front_contacts_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='about_heading',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок на странице "О враче"'),
        ),
        migrations.AlterField(
            model_name='front',
            name='point_1',
            field=models.CharField(blank=True, default='', help_text='Для выделения большими - тег b', max_length=256, verbose_name='Пункт 1 в блоке "О враче"'),
        ),
        migrations.AlterField(
            model_name='front',
            name='point_2',
            field=models.CharField(blank=True, default='', help_text='Для выделения большими - тег b', max_length=256, verbose_name='Пункт 2 в блоке "О враче"'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
    ]
