# Generated by Django 5.0.6 on 2026-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_front_about_heading_alter_front_point_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='-', max_length=256, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='-', max_length=1024, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(default='-', max_length=1024, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
