# Generated by Django 5.0.6 on 2026-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_page_slug_post_url_service_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='url',
            new_name='slug',
        ),
    ]
