# Generated by Django 5.0.6 on 2026-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_rename_url_order_slug_rename_url_post_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='slug',
            new_name='url',
        ),
    ]
