# Generated by Django 5.0.6 on 2026-01-09 15:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_alter_page_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
    ]
