# Generated by Django 5.0.6 on 2026-01-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_alter_service_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('service', 'Услуга'), ('operation', 'Операция')], default=('service', 'Услуга'), max_length=128, verbose_name='Тип поста'),
        ),
    ]
