# Generated by Django 5.0.6 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='work_start_year',
            field=models.PositiveIntegerField(default=2000, verbose_name='Год, с которого начал отсчитываться стаж'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='faq', to='front.service', verbose_name='В каких услугах отображать вопрос'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='760x480', upload_to='posts/', verbose_name='Картинка в списке'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('article', 'Статья'), ('video', 'Видео')], db_index=True, default='article', max_length=16, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('service', 'Услуга'), ('operation', 'Операция')], db_index=True, default='service', max_length=16, verbose_name='Тип услуги'),
        ),
    ]
