# Generated by Django 5.0.6 on 2026-01-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_front_work_start_year_alter_faq_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front',
            name='point_1',
        ),
        migrations.RemoveField(
            model_name='front',
            name='point_2',
        ),
    ]
