# Generated by Django 5.0.6 on 2026-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_remove_front_point_1_remove_front_point_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='front',
            name='address_link',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='front',
            name='address_note',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Сноска под адресом'),
        ),
    ]
