# Generated by Django 5.0.6 on 2026-01-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_front_address_front_address_link_front_address_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='order_link',
            field=models.CharField(default='#', max_length=256, verbose_name='Ссылка на запись'),
        ),
        migrations.AddField(
            model_name='front',
            name='order_modal',
            field=models.BooleanField(default=True, verbose_name='Использовать модалку для записи'),
        ),
    ]
