# Generated by Django 5.0.6 on 2026-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0015_front_order_link_front_order_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default='-', max_length=256, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
