# Generated by Django 5.0.6 on 2026-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_review_email_review_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
