# Generated by Django 5.0.6 on 2026-01-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_alter_review_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
