"""
Django settings for back project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
env = environ.Env()
root = environ.Path(__file__) - 3
environ.Env.read_env(env_file=os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a(ico$20vo#_n*oidbzdgk5iod*tx)vn35=vsy@a-n5sau&b)w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
IS_DEV = env.bool("DEV", default=False)

ALLOWED_HOSTS = ['*']


#
EMAIL_ADMIN = env.str('EMAIL_ADMIN')

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'corsheaders',
    'rest_framework',
	'tinymce',
	'_conf',
	'logs',
	'front',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, '_conf/templates'),
			os.path.join(BASE_DIR, '_conf/templatetags'),
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'_conf.context_processors.venv_variables',
				'front.context_processors.common_data',
			],
		},
	},
]

WSGI_APPLICATION = 'back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}

# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.mysql',   # Backend for connection with Data Base
# 		'NAME': env.str('DB_NAME'),
# 		'USER': env.str('DB_USER'),
# 		'PASSWORD': env.str('DB_PASSWORD'),
# 		'HOST': env.str('DB_HOST'),
# 		'OPTIONS': {
# 			'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#			'charset': 'utf8mb4',
#			'use_unicode': True,
# 		}
# 	}
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_files')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if DEBUG:
	EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
	EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.beget.com"
EMAIL_PORT = 465
EMAIL_HOST_USER = env.str('EMAIL_SITE_EMAIL')
DEFAULT_FROM_EMAIL = env.str('EMAIL_SITE_EMAIL')
EMAIL_HOST_PASSWORD = env.str('EMAIL_SITE_PASSWORD')
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Tinymce.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880 # 5 MB
TINYMCE_JS_URL = os.path.join(STATIC_URL, "tinymce/tinymce.min.js")

TINYMCE_DEFAULT_CONFIG = {
	"height": "480px",
	"width": "100%",
	"relative_urls": False,
	"menubar": "edit view insert table help",
	"plugins":
		'lists link image preview anchor media table help code',
	"toolbar":
		"undo redo | bold italic underline | styles | alignleft aligncenter alignright | numlist bullist | "
		"forecolor backcolor | removeformat | "
		"insertfile image media link | code",
	'style_formats': [
		{ 'title': 'Параграф', 'block': 'p' },
		{ 'title': 'Заголовок 1', 'block': 'h1' },
		{ 'title': 'Заголовок 2', 'block': 'h2' },
		{ 'title': 'Заголовок 3', 'block': 'h3' },
		{ 'title': 'Заголовок 4', 'block': 'h4' },
		{ 'title': 'Заголовок 5', 'block': 'h5' },
		{ 'title': 'Заголовок 6', 'block': 'h6' },
		{ 'title': 'Цитата', 'block': 'blockquote' },
	],
	"images_upload_url": "/_conf/upload_image",
	"custom_undo_redo_levels": 20,
	"language": "ru_RU",
}
