# Generated by Django 5.0.6 on 2026-01-03 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('log_type', models.CharField(max_length=255, verbose_name='Тип записи')),
                ('source', models.CharField(max_length=255, verbose_name='Источник лога')),
                ('desc', models.TextField(blank=True, verbose_name='Описание ошибки')),
                ('json_code', models.TextField(blank=True, verbose_name='JSON')),
                ('request_code', models.TextField(blank=True, verbose_name='Request code')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('trace', models.TextField(blank=True, verbose_name='Подробности ошибки')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи логов',
                'db_table': '_logs',
            },
        ),
    ]
